services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /data/kuzi/:/data:ro
    ports:
      - "5757:5000"
    environment:
      - GUNICORN_CMD_ARGS=-w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
      #- FLASK_ENV=development
      #- PYTHONUNBUFFERED=TRUE
    restart: always
